/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	examplecomv1 "github.com/xigang/kube-crd-controller/pkg/apis/example.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMyCustomResources implements MyCustomResourceInterface
type FakeMyCustomResources struct {
	Fake *FakeExampleV1
	ns   string
}

var mycustomresourcesResource = schema.GroupVersionResource{Group: "example.com", Version: "v1", Resource: "mycustomresources"}

var mycustomresourcesKind = schema.GroupVersionKind{Group: "example.com", Version: "v1", Kind: "MyCustomResource"}

// Get takes name of the myCustomResource, and returns the corresponding myCustomResource object, and an error if there is any.
func (c *FakeMyCustomResources) Get(name string, options v1.GetOptions) (result *examplecomv1.MyCustomResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mycustomresourcesResource, c.ns, name), &examplecomv1.MyCustomResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.MyCustomResource), err
}

// List takes label and field selectors, and returns the list of MyCustomResources that match those selectors.
func (c *FakeMyCustomResources) List(opts v1.ListOptions) (result *examplecomv1.MyCustomResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mycustomresourcesResource, mycustomresourcesKind, c.ns, opts), &examplecomv1.MyCustomResourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &examplecomv1.MyCustomResourceList{ListMeta: obj.(*examplecomv1.MyCustomResourceList).ListMeta}
	for _, item := range obj.(*examplecomv1.MyCustomResourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested myCustomResources.
func (c *FakeMyCustomResources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mycustomresourcesResource, c.ns, opts))

}

// Create takes the representation of a myCustomResource and creates it.  Returns the server's representation of the myCustomResource, and an error, if there is any.
func (c *FakeMyCustomResources) Create(myCustomResource *examplecomv1.MyCustomResource) (result *examplecomv1.MyCustomResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mycustomresourcesResource, c.ns, myCustomResource), &examplecomv1.MyCustomResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.MyCustomResource), err
}

// Update takes the representation of a myCustomResource and updates it. Returns the server's representation of the myCustomResource, and an error, if there is any.
func (c *FakeMyCustomResources) Update(myCustomResource *examplecomv1.MyCustomResource) (result *examplecomv1.MyCustomResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mycustomresourcesResource, c.ns, myCustomResource), &examplecomv1.MyCustomResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.MyCustomResource), err
}

// Delete takes name of the myCustomResource and deletes it. Returns an error if one occurs.
func (c *FakeMyCustomResources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mycustomresourcesResource, c.ns, name), &examplecomv1.MyCustomResource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMyCustomResources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mycustomresourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &examplecomv1.MyCustomResourceList{})
	return err
}

// Patch applies the patch and returns the patched myCustomResource.
func (c *FakeMyCustomResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *examplecomv1.MyCustomResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mycustomresourcesResource, c.ns, name, pt, data, subresources...), &examplecomv1.MyCustomResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*examplecomv1.MyCustomResource), err
}
