
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mycustomresources.example.com
spec:
  group: example.com
  version: v1
  names:
    kind: MyCustomResource
    plural: mycustomresources
  scope: Namespaced