apiVersion: example.com/v1
kind: MyCustomResource
metadata:
  name: example-myresource
spec:
  message: hello world
  someValue: 13
[root@q11512v customresource]# cat resource.yaml 
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mycustomresources.example.com
spec:
  group: example.com
  version: v1
  names:
    kind: MyCustomResource
    plural: mycustomresources
  scope: Namespaced